
import styles from '../../styles/Movies.module.css'
import Head from 'next/head'
import Link from 'next/link'
import users from '../../database/user.json'
import { useEffect, useState } from 'react'
import Router from 'next/router'

var user=users;



export default function Video(){

    return <div className={styles.container}>
    <Head>
      <title>Ndizi TV</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
        <div className={styles.videoplayer}>
            <Link href="/">Back</Link>
            <video controls="controls"  autoPlay style={{ width: '100vw', height: '100vh' }}>
                <source src="http://media.w3.org/2010/05/sintel/trailer.mp4" />
            </video>
        </div>
    </main>
</div>
}